/**************************************************************
 * HTTPPrint.h
 * Provides callback headers and resolution for user's custom
 * HTTP Application.
 * 
 * This file is automatically generated by the MPFS Utility
 * ALL MODIFICATIONS WILL BE OVERWRITTEN BY THE MPFS GENERATOR
 **************************************************************/

#ifndef __HTTPPRINT_H
#define __HTTPPRINT_H

#include "TCPIP Stack/TCPIP.h"

#if defined(STACK_USE_HTTP2_SERVER)

extern HTTP_CONN curHTTP;
extern HTTP_STUB httpStubs[MAX_HTTP_CONNECTIONS];
extern BYTE curHTTPID;

void HTTPPrint(DWORD callbackID);
void HTTPPrint_hellomsg(void);
void HTTPPrint_version(void);
void HTTPPrint_builddate(void);
void HTTPPrint_rebootaddr(void);
void HTTPPrint_reboot(void);
void HTTPPrint_config_hostname(void);
void HTTPPrint_config_ip(void);
void HTTPPrint_config_gw(void);
void HTTPPrint_config_subnet(void);
void HTTPPrint_config_dns1(void);
void HTTPPrint_config_dns2(void);

void HTTPPrint(DWORD callbackID)
{
	switch(callbackID)
	{
		case 0x0000000d:
			HTTPIncFile((ROM BYTE*)"header.inc");
			break;
		case 0x0000000f:
			HTTPPrint_hellomsg();
			break;
		case 0x00000010:
			HTTPIncFile((ROM BYTE*)"footer.inc");
			break;
		case 0x0000001c:
			HTTPPrint_version();
			break;
		case 0x0000001d:
			HTTPPrint_builddate();
			break;
		case 0x0000001e:
			HTTPPrint_rebootaddr();
			break;
		case 0x0000001f:
			HTTPPrint_reboot();
			break;
		case 0x00000021:
			HTTPPrint_config_hostname();
			break;
		case 0x00000023:
			HTTPPrint_config_ip();
			break;
		case 0x00000024:
			HTTPPrint_config_gw();
			break;
		case 0x00000025:
			HTTPPrint_config_subnet();
			break;
		case 0x00000026:
			HTTPPrint_config_dns1();
			break;
		case 0x00000027:
			HTTPPrint_config_dns2();
			break;
		default:
			// Output notification for undefined values
			TCPPutROMArray(sktHTTP, (ROM BYTE*)"!DEF", 4);
	}

	return;
}

void HTTPPrint_(void)
{
	TCPPut(sktHTTP, '~');
	return;
}

#endif

#endif
